export interface AboutTocItem {
  id: string
  label: string
}

export interface AboutTextItem {
  title: string
  body: string
}

export const DEFAULT_ABOUT_PAGE = {
  heroEyebrow: 'Section 1 · Our Foundation',
  heroHeading: 'About DCMAC',
  version: '1.1',
  date: 'August 31, 2025',
  lede: 'Welcome to the Door County Mutual Aid Collective! This is your essential guide to our collective work.',
  tocAriaLabel: 'On this page',
  toc: [
    { id: 'introduction', label: 'Introduction' },
    { id: 'mission', label: 'Mission' },
    { id: 'principles', label: 'Guiding Principles' },
    { id: 'norms-tldr', label: 'Norms TLDR' },
    { id: 'collective-norms', label: 'Collective Norms' },
    { id: 'security', label: 'Security Norms' },
    { id: 'security-meetings', label: 'Security at Meetings' },
  ],
  introductionHeading: 'Introduction',
  introductionParagraphs: [
    'Its purpose is to provide clear guidelines for all our activities, ensuring consistency, safety, legal compliance, and most importantly, alignment with our mission, philosophy, and values. By following these procedures, we ensure we operate effectively, respectfully, and sustainably for the benefit of all in the Door Peninsula.',
    'This guidebook is a living document. Please use it as your primary reference and reach out to our coordinators or relevant working groups if you have questions. We regularly review and revise it, so your feedback is always welcome to help us improve.',
  ],
  missionTitle: 'Our Mission',
  missionBody: 'At Door County Mutual Aid, we bridge community needs and resources by creating inclusive networks of support that challenge systemic inequities and educating and empowering impassioned individuals to take direct action toward lasting change.',
  principlesHeading: 'Our Guiding Principles',
  principlesIntro: 'The deeper "how" and "why" behind our work — dynamic principles that inform every interaction and effort within the collective.',
  principles: [
    { title: 'Community-Focused Mutual Aid', body: 'We operate from a vision centered on community well-being, built around mutual support, shared resources, decentralized power, and individual empowerment. We believe collective well-being is a shared responsibility, not a service to be delivered, fostering a culture of solidarity over charity.' },
    { title: 'Individual Autonomy', body: 'We honor that each person is the exclusive controller of their body, energy, and life. Participation is on one\'s own terms, and we structure our efforts to limit any coercion or control that could interfere with self-direction and empowerment.' },
    { title: 'Distributed Power', body: 'We strive for an equitable distribution of influence, ensuring that people work together on equal footing, and no one holds disproportionate power over another. Decisions are made collaboratively, accessing the collective experience and wisdom of the group.' },
    { title: 'Direct Action & Projects', body: 'We prioritize creating change and addressing needs directly within the community, without relying solely on external institutions or indirect methods. We focus on projects that foster community support, education, give people a sense of their own power, and shift influence from hierarchies to people and communities — as well as building toward a long-term vision of a healthy, just, and flourishing community.' },
    { title: 'Radical Love & Collective Liberation', body: 'Our work is fueled by a deep love and care for ourselves, our neighbors, and the earth/planet. We are committed to solidarity, especially with those politically targeted and suffering under systems of oppression. We actively seek to dismantle all interlocking systems of oppression.' },
    { title: 'Strategic Nonviolence & Self-Determination', body: 'As a collective, we mobilize using strategic nonviolence in our actions. Simultaneously, we respect the inherent right of individuals and communities to determine how to protect/direct themselves.' },
    { title: 'Inclusivity & Accessibility', body: 'We welcome anyone interested in the mission and principles of DCMAC. We actively strive to maintain accessibility in our collective spaces and proactively take accountability to improve in areas where we may fall short.' },
    { title: 'Responsiveness & Adaptability', body: 'We value continuous input and dialogue with the community, seeking to respond directly to needs and concerns. We accept responsibility for our actions and maintain flexible, adaptable structures to plan for changing conditions and ensure swift, easy engagement.' },
    { title: 'Joyous & Wholehearted Engagement', body: 'In spite of the struggles we face, we strive to find joy in each other and bring playfulness to our projects. We encourage bringing our whole selves to this group, respecting the often emotional nature of social justice work, collective process, and setting aside egos to appreciate everyone for who they are.' },
    { title: 'Education, Dialogue & Growth', body: 'We are dedicated to continuous collective learning and open communication. We foster environments where knowledge is shared freely, diverse perspectives are welcomed, and critical thinking is encouraged to deepen our understanding and strengthen our collective action. We consistently seek opportunities to educate and improve ourselves, learning from successes and failures to strengthen future initiatives.' },
    { title: 'Continuous Inquiry', body: 'We believe in the power of constant questioning — of our methods, our assumptions, and the systems around us. We encourage a spirit of curiosity and critical analysis, recognizing that a willingness to challenge established norms and learn from every experience is essential for true growth and liberation.' },
  ],
  shortNormsHeading: 'Short Norms TLDR',
  shortNormsIntro: 'A quick summary of agreed-upon norms.',
  shortNorms: [
    'No intentional oppression',
    'Assume best intentions',
    'Make space, take space — be aware of the space you\'re taking up',
    'Act in solidarity, not charity',
    'Treat each other with respect',
    'Yes to passion. No to obligation.',
    'Ask for support if you need it / offer support if you can',
    'All types of contributions are welcome',
    'We strive for full inclusion',
    'We value feedback',
    'Dissent and questions are a gift to the group',
    'Vulnerability and sharing emotions are encouraged',
    'Meetings and events are spaces for our whole selves; any way you are comfortable is OK!',
  ],
  collectiveNormsHeading: 'Collective Norms',
  collectiveNormsIntro: 'The actionable traits we embody — how we show up and what we prioritize in our daily work.',
  collectiveNorms: [
    { title: 'Assume Best Intentions', body: 'We are all working towards the same goals; as such, we strive to view the variety of individual expressions and actions through the lens of curiosity and camaraderie. Even so, we are accountable for the impacts of our actions and value feedback.' },
    { title: 'You Have Permission to Be Imperfect', body: 'Fear of making mistakes prevents privileged individuals from showing up to challenge the status quo. Let the expectation be that everyone will make mistakes, and those mistakes offer opportunities for learning and dialogue.' },
    { title: 'No Masters', body: 'We are a nonhierarchical collective of community members. No single person is in charge. We all have an equal voice.' },
    { title: 'No Flakes', body: 'You are responsible for the commitments you make. We move forward only if we are bonded to our words.' },
    { title: 'No Ego', body: 'Our actions are about service to our community, not personal agendas.' },
    { title: 'Feedback Is a Gift', body: 'We are all learning and growing. We learn and grow through direct communication, reflection, and discussion. We seek out opportunities to give and receive constructive feedback.' },
    { title: 'Collaborative Decision-Making', body: 'We want to access the collective experience and wisdom of the Collective when making decisions. We utilize structures that encourage the broadest input possible.' },
    { title: 'Visionary', body: 'We believe a better world is possible. We will not allow appeasements or concessions to distract our focus from the larger vision of an awesome future.' },
    { title: 'Revolutionary Hope & Optimism', body: 'Hope as revolutionary patience means to be prepared to take action when the moment presents itself — to acknowledge and embrace uncertainty and the unknown, believing in the possibility of positive change despite overwhelming odds or difficult circumstances. We do not deny the devastating realities in our communities but face them while remembering progress that has been achieved by other movements for change. Revolutionary optimism challenges us to believe in the possibility of a radical future in order to fight, to cultivate hope and fight nihilism and doomerism that seek to divide and diminish our community.' },
    { title: 'Group Education & Growth', body: 'As group praxis, we consistently seek opportunities to train and educate ourselves to improve in our organizing, our politics, and ourselves.' },
    { title: 'Structured for Change', body: 'We use adaptable structures that plan for changing conditions and create space for people to engage quickly and easily.' },
    { title: 'Flexibility', body: 'Every situation is unique and requires attention to its specific context. We use our principles, norms, and precedents to guide us, not to coerce people.' },
    { title: 'Fight Organization Inertia', body: 'Try something new! Continue to analyze the organization, its processes, these principles, and creatively work to improve the collective.' },
    { title: 'Question Everything', body: 'A skill set that can be developed by practicing the following: challenge assumptions, seek evidence, consider alternative perspectives, and open-mindedness.' },
  ],
  securityHeading: 'DCMA Security Norms',
  securityIntro: 'Security culture is a set of practices and attitudes designed to increase the safety of political communities. These guidelines are created based on recent and historic state repression, and help to reduce paranoia and increase effectiveness. The central principle of security culture is that people should never be privy to any sensitive information they do not need to know.',
  securityTldr: 'Keep sensitive information inside the circle of people it concerns, collaborate with reliable and experienced community members whose history you can verify, and don\'t give away anything about your private activities.',
  securityContext: 'DCMAC is a public and above-ground group. We welcome people with different comfort levels and experience with activism and direct action. We don\'t want to expose people to danger that they haven\'t signed up for.',
  securityItems: [
    'People should never be aware of sensitive information they do not need to know — don\'t ask, don\'t tell.',
    'Don\'t share personally identifying information about yourself or others.',
    'What we say and don\'t say, what we type and don\'t type is our best defence from the state. Protecting people\'s identities is our best defence.',
    'Use discretion when speaking with law enforcement. Know and actively educate yourself of your rights.',
    'Know that you can say "no" at any time to anyone about anything. Don\'t answer questions or participate in any projects you don\'t feel good about.',
    'Don\'t imperil others with your decisions. Consider your actions and the impact they can have. Remember: jokes can be taken seriously.',
  ],
  securityConfrontationalHeading: 'If you\'re going to organize confrontational/arrestable (initiating confrontation that interferes with other group\'s activities) protests or actions:',
  securityConfrontationalItems: [
    'Utilize affinity groups (small groups of trusted people)',
    'Organize in person as much as possible',
    'Be conscious of the locations you choose to organize in and consider the risks.',
    'If organizing online, do it in an encrypted system and only where you know everyone (affinity group).',
  ],
  securityMeetingsHeading: 'Security Norms at Meetings',
  securityMeetingItems: [
    'We want DCMA meetings to be welcoming and not intimidating.',
    'Respect other people\'s right to not know things.',
    'Be aware of who is in the space — how much do you know/trust everyone around you?',
    'Don\'t say anything in the meeting space you wouldn\'t want to see on the internet.',
    'This is a space to talk about the projects that we are excited for the community to know about — projects where we want to invite all people who want to help to get involved.',
    'Don\'t take notes on sensitive information; pause recording if needed at meetings.',
    'Use first name or aliases in notes depending on individual preference.',
  ],
  seo: {
    title: 'About | Door County Mutual Aid',
    description: 'Mission, guiding principles, collective norms, and security culture for the Door County Mutual Aid Collective.',
  },
} as const
